### ISSUE TITLE
Restoring Backups

### ISSUE THREAD

**Issue by leouofa** [coorasse/heroku-api-postgres#1]
I'd like to help with a PR to restore pg backups. @coorasse could you point me in the right direction?

**Comment by coorasse** [comment]
Of course. Very glad to receive some help to bring this gem forward! 
Since I use the same API of the CLI, you can check how the restore is implemented here: https://github.com/heroku/heroku-pg/blob/master/commands/backups/restore.js

Seems like you need a [get to retrieve the backup](https://github.com/heroku/heroku-pg/blob/master/commands/backups/restore.js#L39) and then a [post to restore it](https://github.com/heroku/heroku-pg/blob/master/commands/backups/restore.js#L57)

This will run asynchronously, so probably is a good idea to also implement the api to check the progress and the api to cancel the restore (check always the same file). 
I hope this helps you.

**Comment by coorasse** [comment]
You can now restore a dump from a public url with: `restore = backups_client.restore(database_id, dump_url)`. only public urls are supported for now.

**Comment by leouofa** [comment]
Thank you!
